# See ../../charts/ingress-nginx/values.yaml for full list of features
image:
  name: nginx
  tag: 1.22.0
  pullPolicy: IfNotPresent

services:
  - name: "http" # name "http" binds to http listeners 
    type: HostPort
    hostPort: 80
    containerPort: 80
  - name: "https" # name "https" binds to https listeners 
    type: HostPort
    hostPort: 443
    containerPort: 443


confd:
  enabled: true
  files:
    tekton.cogitogroup.co.uk.conf: 
      ssl_cert_dir_name: tekton-cogitogroup-co-uk
      ssl_cert_existing_secret_name: tekton-cogitogroup-co-uk # contains tls.key and tls.crt 
      server_name: tekton.cogitogroup.co.uk
      backend_host: el-dev-listener.default.svc.cluster.local
      backend_port: 8080


rollingUpdateMaxUnavailable: 1 # 1 is the minimum available value for this field when using DaemonSet

ssl:
  enabled: false