apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubectl-restart-deployment-
spec:
  taskRef:
    name: kubectl-restart-deployment
  params:
    - name: deployment
      value: api-app
    - name: namespace
      value: stg-dummy
  workspaces:
    - name: kubeconfig-dir
      configMap:
        name: "kube-config"