apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ort-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: ort
  params:
  - name: git_revision
    value: "feature/tekton-ort"
  workspaces:
    - name: git-pvc
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: image-cache
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-creds
      secret:
        secretName: "pipelines-ssh-key"
    - name: docker-creds-cm
      secret:
        secretName: "pipelines-docker-config"
    - name: kubeconfig
      configMap:
        name: "pipelines-kube-config"