apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dev-
spec:
  pipelineRef:
    name: dev
  workspaces:
    - name: git-pvc
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-creds
      secret:
        secretName: "template-pipeline-ssh-key"
    - name: docker-creds-cm
      secret:
        secretName: "template-pipeline-docker-config"
    - name: kubeconfig
      configMap:
        name: "template-pipeline-kube-config"