{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  params:
  - name: git_revision
    description: The git revision
    default: "master"
  - name: git_revision_owner
    description: The owner of the git revision
    default: "git_owner_default_value"
  - name: git_repository_name
    description: The name of the git repository
    default: "git_repository_name_default_value"
  workspaces:
    - name: git-pvc
    - name: image-cache
    - name: ssh-creds
    - name: docker-creds-cm
    - name: kubeconfig
  tasks:
{{ if $value.custom.enabled }}
{{- range $task := $value.custom.tasks }}
    - name: {{ $task.name }}
      taskRef:
        name: {{ $task.name }}
{{ if $task.params }}
      params:
{{- with $task.params -}}
{{ $yaml := . }}
{{- range $line := $yaml }}
{{- range $key, $v := $line -}}
{{ if eq $key "name" }}
      - {{ $key }}: {{ $v }}
{{- end -}}
{{ if eq $key "value" }}
        {{ $key }}: {{ $v | quote}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}
{{ with $value.tasks }}
    - name: started-webhook
      taskRef:
        name: send-to-webhook-slack
      params:
      - name: {{ $.Values.secret_slack_webhook }}
        value: "{{ include "generic.fullname" $ }}-{{ $.Values.secret_slack_webhook }}"
      - name: git_revision_owner
        value: $(params.git_revision_owner)
      - name: git_repository_name
        value: $(params.git_repository_name)
      - name: message
        value: "Started pipeline"
      - name: helm_release_name
        value: "{{ include "generic.fullname" $ }}"
      - name: pipeline_name
        value: "{{ $value.name }}"
      - name: bot-name
        value: "*TEKTON-stg-dummy-test*"
      - name: icon-emoji
        value: https://tekton.dev/favicons/favicon.ico
    - name: {{ .clone.name }}
{{ .clone | toYaml | indent 6}}
      taskRef:
        name: "{{ include "generic.fullname" $ }}-git-clone"
    - name: {{ .build.name }}
{{ .build | toYaml | indent 6}}
      taskRef:
        name: "{{ include "generic.fullname" $ }}-kaniko"
    - name: mid-webhook
      taskRef:
        name: send-to-webhook-slack
      params:
      - name: {{ $.Values.secret_slack_webhook }}
        value: "{{ include "generic.fullname" $ }}-{{ $.Values.secret_slack_webhook }}"
      - name: git_revision_owner
        value: $(params.git_revision_owner)
      - name: git_repository_name
        value: $(params.git_repository_name)
      - name: helm_release_name
        value: "{{ include "generic.fullname" $ }}"
      - name: pipeline_name
        value: "{{ $value.name }}"
      - name: message
        value: "Pushed {{ (index .build.params 0).value }}/{{ (index .build.params 1).value }}:$(params.git_revision)"
      - name: bot-name
        value: "*TEKTON-stg-dummy-test*"
      - name: icon-emoji
        value: https://tekton.dev/favicons/favicon.ico
      runAfter:
        - build-and-push
    - name: update-image
      taskRef:
        name: kubectl-restart-deployment
      params:
        - name: deployment
          value: {{ $value.deployment_name }}
        - name: tag
          value: $(params.git_revision)
        - name: git_repository_name
          value: $(params.git_repository_name)
        - name: docker_registry
          value: {{ (index .build.params 0).value }}
        - name: docker_repository
          value: {{ (index .build.params 1).value }}
        - name: namespace
          value: {{ $value.deployment_namespace }}
      runAfter:
        - build-and-push
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig
    - name: end-webhook
      taskRef:
        name: send-to-webhook-slack
      params:
      - name: {{ $.Values.secret_slack_webhook }}
        value: "{{ include "generic.fullname" $ }}-{{ $.Values.secret_slack_webhook }}"
      - name: git_revision_owner
        value: $(params.git_revision_owner)
      - name: git_repository_name
        value: $(params.git_repository_name)
      - name: helm_release_name
        value: "{{ include "generic.fullname" $ }}"
      - name: pipeline_name
        value: "{{ $value.name }}"
      - name: message
        value: "Deployed {{ $value.deployment_namespace }}/{{ $value.deployment_name }}"
      - name: bot-name
        value: "*TEKTON-stg-dummy-test*"
      - name: icon-emoji
        value: https://tekton.dev/favicons/favicon.ico
      runAfter:
        - update-image
---
{{- end }}
{{- end }}
{{- end -}}