{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  workspaces:
    - name: git-pvc
    - name: ssh-creds
    - name: docker-creds-cm
    - name: kubeconfig
  tasks:
    - name: started-webhook
      taskRef:
        name: send-to-webhook-slack
      params:
      - name: {{ $.Values.secret_slack_webhook }}
        value: "{{ include "generic.fullname" $ }}-{{ $.Values.secret_slack_webhook }}"
      - name: message
        value: "INFO [{{ include "generic.fullname" $ }}] Starting"
      - name: bot-name
        value: "*TEKTON-stg-dummy-test*"
      - name: icon-emoji
        value: https://tekton.dev/favicons/favicon.ico
    - name: clone-git-repo
      taskRef:
        name: "{{ include "generic.fullname" $ }}-git-clone"
      params:
      - name: url
        value: {{ $value.git_source }} 
      - name: {{ $value.git_specifier}}
        value: {{ $value.git_branch_or_commit }}
      workspaces:
      - name: ssh-directory
        workspace: ssh-creds
      - name: output
        workspace: git-pvc
      runAfter:
        - started-webhook
    - name: build-and-push
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: {{ $value.docker_registry }}
      runAfter:
        - clone-git-repo
      workspaces:
      - name: source
        workspace: git-pvc
      - name: dockerconfig
        workspace: docker-creds-cm
    - name: mid-webhook
      taskRef:
        name: send-to-webhook-slack
      params:
      - name: {{ $.Values.secret_slack_webhook }}
        value: "{{ include "generic.fullname" $ }}-{{ $.Values.secret_slack_webhook }}"
      - name: message
        value: "INFO [{{ include "generic.fullname" $ }}] Built and pushed"
      - name: bot-name
        value: "*TEKTON-stg-dummy-test*"
      - name: icon-emoji
        value: https://tekton.dev/favicons/favicon.ico
      runAfter:
        - build-and-push
    - name: update-image
      taskRef:
        name: kubectl-restart-deployment
      params:
        - name: deployment
          value: {{ $value.deployment_name }}
        - name: namespace
          value: {{ $value.deployment_namespace }}
      runAfter:
        - build-and-push
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig
    - name: end-webhook
      taskRef:
        name: send-to-webhook-slack
      params:
      - name: {{ $.Values.secret_slack_webhook }}
        value: "{{ include "generic.fullname" $ }}-{{ $.Values.secret_slack_webhook }}"
      - name: message
        value: "INFO [{{ include "generic.fullname" $ }}] Finished"
      - name: bot-name
        value: "*TEKTON-stg-dummy-test*"
      - name: icon-emoji
        value: https://tekton.dev/favicons/favicon.ico
      runAfter:
        - update-image
{{- end }}
{{- end }}