{{- if .Values.routes }}
{{- range $value := .Values.routes }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 60s
  labels:
    app: {{ $value.name }}
    domain: {{ $value.host }}
    service: {{ $value.name }}
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  host: {{ $value.host }}
  port:
    targetPort: {{ $value.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ $value.serviceName }}
    weight: 100
  wildcardPolicy: None
---
{{- end }}
{{- end }}
