{{- if .Values.services }}
{{- range $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "generic.fullname" $ }}-{{ $value.name }}"
  namespace: {{ $.Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
{{ if $value.annotations }}
{{ with $value.annotations }}
{{ .| toYaml | indent 4}}
{{ end }}
{{ end }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
spec:
  type: {{ $value.type }}
  ports:
    - name: {{ $value.name }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      {{ if and (eq $value.type "NodePort") ($value.nodePort)}}
      nodePort: {{ $value.nodePort }}
      {{ end }}
      protocol: {{ $value.protocol }}
  selector:
    {{ if $value.selector }}
    {{ with $value.selector }}
{{ . | toYaml | indent 4}}
    {{ end }}
    {{ end }}
---
{{- end }}
{{- end }}
