{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
{{ if $value.custom }}
{{ with $value.custom }}
{{- range $sa := .serviceAccounts }}
---
{{ .yaml }}
{{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
---