kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
nodes:
- role: control-plane
  extraPortMappings:
  # Ingress-nginx proxy 
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 433
    hostPort: 443
    listenAddress: "0.0.0.0"
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "0.0.0.0"
  extraMounts:
  - hostPath: /var/lib/docker
    containerPath: /var/lib/docker
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  - hostPath: /Users/george/dev/hashgraph/hedera-nft-auction-demo/docker-files
    containerPath: /mnt/docker-files