
secret_slack_webhook_uri: 
pipelines:
  - name: prod 
    # Clone task
    git_source: git@github.com:dockerised/docker-anyconnect-vpn.git
    git_specifier: revision #revision/commit
    git_branch_or_commit: master #master/SHA256
    # Build task
    docker_registry: george7522/docker-anyconnect-vpn
    # Deploy task
    deployment_name: nginx-app
    deployment_namespace: default
  - name: dev
    # Clone task
    git_source: git@github.com:dockerised/docker-anyconnect-vpn.git
    git_specifier: revision #revision/commit
    git_branch_or_commit: dev #master/SHA256
    # Build task
    docker_registry: george7522/docker-anyconnect-vpn
    # Deploy task
    deployment_name: nginx-app
    deployment_namespace: default

