# See ../../charts/common/values.yaml for full list of features

replicaCount: 1

image: 
  repository: nginx
  tag: "1.22.0"
  pullPolicy: "Always"

services:
 - name: http
   type: ClusterIP
   containerPort: 80
   targetPort: 80
   protocol: TCP