
pipelines:
  - name: alpha-worker
    trigger:
      git_revisions: ['refs/heads/cicd-alpha']
      eventTypes: ["push"]
      token: ""
    taskcall:
    - name: git-clone
      taskRef:
        name: "git-clone"
      params:
      - name: url
        value: git@github.com:coolcatsnft/coolcats-nodejs-server
      - name: revision #revision/commit
        value: $(params.git_revision)
      workspaces:
      - name: ssh-directory
        workspace: ssh-creds
      - name: output
        workspace: git-pvc
    - name: git-clone-infra
      taskRef:
        name: "git-clone"
      params:
      - name: url
        value: git@github.com:coolcatsnft/aws-eks-infrastructure
      - name: revision #revision/commit
        value: feature/tekton
      workspaces:
      - name: ssh-directory
        workspace: ssh-creds
      - name: output
        workspace: git-pvc
      runAfter:
        - ecr-build-push
    - name: ecr-build-push
      description: >-
        This task does a AWS CLI command to login to ECR, builds and pushes the docker image to ECR 
      taskRef:
        name: ecr-build-push
      runAfter:
        - git-clone
      params:
      - name: app_short_name
        value: "worker"
      - name: AWS_ECR_ACCOUNT_ID
        value: "683746102303"
      - name: AWS_REGION
        value: "us-east-1"
      - name: docker_tag_version
        value: $(params.git_revision)
      - name: stage
        value: "alpha"
      - name: arch
        value: "defaultarch"
      workspaces:
      - name: git-pvc
        workspace: git-pvc
    - name: helm-deploy
      taskRef:
        name: helm-deploy
      workspaces:
      - name: git-pvc
        workspace: "git-pvc"
      runAfter:
      - ecr-build-push
      params:
      - name: app_short_name
        value: "worker"
      - name: docker_tag_version
        value: $(params.git_revision)
      - name: stage
        value: "alpha"
    custom:
      enabled: false