apiVersion: v1
kind: Secret
type: generic
metadata:
  name: "{{ include "generic.fullname" . }}-{{ $.Values.secret_docker_conf }}"
  namespace: {{ $.Release.Namespace }}
data:
  config.json: {{ $.Values.docker_config_json | b64enc -}}