{{ if .Values.secret_slack_webhook_uri }} 
apiVersion: v1
kind: Secret
type: generic
metadata:
  name: "{{ include "generic.fullname" . }}-{{ $.Values.secret_slack_webhook }}"
  namespace: {{ $.Release.Namespace }}
data:
  url: {{ $.Values.secret_slack_webhook_uri | b64enc -}}
{{ end }} 