secret_ssh_cred: ssh-key
secret_docker_conf: docker-config
docker_config_json: 
configmap_kube_conf: kube-config
secret_slack_webhook_uri: 

pipelines:
  - name: prod 
    params:
    - name: git_revision
      description: The git revision
      default: "master"
    - name: git_revision_owner
      description: The owner of the git revision
      default: "git_owner_default_value"
    - name: git_branch_name
      description: The name of branch for the git revision
      default: "git_branch_name_default_value"
    - name: git_repository_name
      description: The name of the git repository
      default: "git_repository_name_default_value"
    workspaces:
      - name: git-pvc
      - name: image-cache
      - name: ssh-creds
      - name: docker-creds-cm
    trigger:
      eventTypes: [ "pull_request" ]
      eventActions: "['opened','synchronize','reopened']"
    taskcall:
    - name: git-clone
      taskRef:
        name: "git-clone"
      params:
      - name: url
        value: git@github.com:cogitogroupltd/docker-nginx-hello-world
      - name: revision #revision/commit
        value: $(params.git_revision)
      workspaces:
      - name: ssh-directory
        workspace: ssh-creds
      - name: output
        workspace: git-pvc
    - name: buildah-build-push
      taskRef:
        name: buildah-build
      params:
      - name: IMAGE
        value: cogitoexample/docker-nginx-hello-world
      runAfter:
      - git-clone
      workspaces:
      - name: source
        workspace: git-pvc
      - name: dockerconfig
        workspace: docker-creds-cm
    - name: rolling-update
      taskRef:
        name: rolling-update
      admin: true
      params:
      - name: deployment
        value: nginx-app
      - name: namespace
        value: default
      - name: tag
        value: $(params.git_revision)
      - name: git_repository_name
        value: $(params.git_repository_name)
      - name: docker_registry
        value: cogitoexample
      - name: docker_repository
        value: docker-nginx-hello-world
      runAfter:
      - buildah-build-push