apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "cluster-administrator-{{ .Release.Namespace }}-{{ .Release.Name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ include "generic.fullname" $ }}-tekton-default-sa"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io