apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "generic.fullname" $ }}-{{ $.Values.configmap_kube_conf }}"
  namespace: {{ $.Release.Namespace }}
data:
  kubeconfig: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: DUMMY
        server: https://A5494263581FF77B9E1B5EDA88421698.gr7.eu-west-2.eks.amazonaws.com
      name: arn:aws:eks:eu-west-2:676312345602:cluster/staging-eks-private
    contexts:
    - context:
        cluster: arn:aws:eks:eu-west-2:676312345602:cluster/staging-eks-private
        namespace: default
        user: arn:aws:eks:eu-west-2:676312345602:cluster/staging-eks-private
      name: arn:aws:eks:eu-west-2:676312345602:cluster/staging-eks-private
    current-context: arn:aws:eks:eu-west-2:676312345602:cluster/staging-eks-private
    kind: Config
    preferences: {}
    users:
    - name: arn:aws:eks:eu-west-2:676312345602:cluster/staging-eks-private
      user:
        exec:
          apiVersion: client.authentication.k8s.io/v1alpha1
          args:
          - --region
          - eu-west-2
          - eks
          - get-token
          - --cluster-name
          - staging-eks-private
          command: aws
          interactiveMode: IfAvailable
          provideClusterInfo: false