{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ $value.name }}-listener
  namespace: {{ $.Release.Namespace }}
spec:
  serviceAccountName: "{{ include "generic.fullname" $ }}-tekton-triggers-sa"
  triggers:
  - bindings:
      - ref: {{ $value.name }}
  triggers:
  - name: custom-resource-listener
    interceptors:
      - name: "only when PRs are opened"
        ref:
          name: "cel"
        params:
          {{ if eq $value.trigger.eventType "push" }}
          - name: "filter"
            value: "body.ref in ['refs/heads/{{ $value.git_revision }}']"
          {{ end }}
          {{ if eq $value.trigger.eventType "pull_request" }}
          - name: "filter"
            value: "body.action in ['opened', 'synchronize', 'reopened']"
          {{ end }}
    template:
      ref: {{ $value.name }}
---
{{- end }}
{{- end }}