{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
{{- if $value.trigger }}
{{- with $value.trigger }}
{{- if .token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}-github-token
type: Opaque
data:
  token: {{ .token | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

