kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-role"
  namespace: {{ $.Release.Namespace }}
rules:
- apiGroups:
  - tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - pipelineresources
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  verbs:
  - create
- apiGroups:
  - triggers.tekton.dev
  resources:
  - triggerbindings
  - triggers
  - triggertemplates
  - eventlisteners
  - clusterinterceptors
  - clustertriggerbindings
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-cr"
rules:
- apiGroups:
  - tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - pipelineresources
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  verbs:
  - create
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clusterinterceptors
  - clustertriggerbindings
  - interceptors
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-crb"
subjects:
  - kind: ServiceAccount
    name: "{{ include "generic.fullname" $ }}-tekton-triggers-sa"
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-cr"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-sa"
  namespace: {{ $.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-rb"
  namespace: {{ $.Release.Namespace}}
subjects:
- kind: ServiceAccount
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-sa"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "generic.fullname" $ }}-tekton-triggers-role"
---