{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
{{- if $value.trigger }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  params:
  - name: git_revision
{{ with $value.trigger }}
{{ if .eventTypes }}
{{- range $event := .eventTypes }}
{{ if eq $event "pull_request" }}
    value: $(body.pull_request.head.sha)
{{ end }}
{{ end }}
{{ end }}
{{ if .eventTypes }}
{{- range $event := .eventTypes }}
{{ if eq $event "push" }}
    value: $(body.head_commit.id)
{{ end }}
{{ end }}
{{ end }}
  - name: namespace
    value: default
  - name: git_source
    value: $(body.repository.html_url)
  - name: git_repository_name
    value: $(body.repository.name)
  - name: git_branch_name
    value: $(body.ref)
  - name: git_revision_owner
{{ if eq .eventType "pull_request" }}
    value: $(body.pull_request.head.user.login)
{{ end }}
{{ if eq .eventType "push" }}
    value: $(body.pusher.name)
{{ end }}
{{ end }}
---
{{- end }}
{{- end }}
{{- end }}