{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace}}
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        {{ if $value.trigger.eventType }}
        - name: "filter"
          value: "header.match('X-GitHub-Event') == '{{ $value.trigger.eventType}}'"
        {{ end }}
        {{ if eq $value.trigger.eventType "push" }}
        - name: "filter"
          value: "body.ref in ['refs/heads/{{ $value.git_revision }}']"
        {{ end }}
        {{ if eq $value.trigger.eventType "pull_request" }}
        - name: "filter"
          value: "body.action in ['opened', 'synchronize', 'reopened']"
        {{ end }}
        - name: "overlays"
          value:
            - key: extensions.truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
  bindings:
  - ref: {{ $value.name }}
  template:
    ref: {{ $value.name }}
---
{{- end }}
{{- end }}
