apiVersion: tekton.dev/v1beta1
metadata:
  generateName: git-clone-taskrun-
kind: TaskRun
spec:
  taskRef:
    name: dummy-build-git-clone
  params:
    - name: url
      value: https://github.com/cogitogroupltd/docker-anyconnect-vpn.git
  workspaces:
  - name: ssh-directory
    secret:
      secretName: "ssh-key"
  - name: output
    emptyDir: {}
    # persistentVolumeClaim:
    #   claimName: git-clone-output