kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "generic.fullname" . }}-{{ $.Values.secret_ssh_cred }}"
  namespace: {{ $.Release.Namespace }}
data:
  id_rsa: {{ $.Values.secret_ssh_key | b64enc -}}