apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: example-kaniko-
  namespace: tekton-resources
spec:
  pipelineRef:
    name: prod
  params:
  - name: git_revision
    value: latest
  taskRunSpecs:
    - pipelineTaskName: rolling-update # ref from values-override.yaml pipelines[].prod.taskcall.name
      taskServiceAccountName: pipelines-tekton-resources-rolling-update # ref from templates/global/serviceAccount.yaml
  workspaces:
    - name: git-pvc
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: image-cache
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-creds
      secret:
        secretName: "pipelines-ssh-key"
    - name: docker-creds-cm
      secret:
        secretName: "pipelines-docker-config"
    - name: kubeconfig
      configMap:
        name: "pipelines-kube-config"