secret_ssh_key:
secret_ssh_cred: ssh-key
secret_docker_conf: docker-config
docker_config_json: 
configmap_kube_conf: kube-config
secret_slack_webhook_uri: 

pipelines:
  - name: prod 
    trigger:
      eventTypes: [ "pull_request" ]
      eventActions: "['opened','synchronize','reopened']"
    tasks:
      clone:
        name: clone-git-repo
        params:
        - name: url
          value: git@github.com:dockerised/docker-anyconnect-vpn.git
        - name: revision #revision/commit
          value: $(params.git_revision)
        workspaces:
        - name: ssh-directory
          workspace: ssh-creds
        - name: output
          workspace: git-pvc
        runAfter:
        - started-webhook
      build:  
        name: build-and-push
        params:
          - name: DOCKER_REGISTRY
            value: george7522
          - name: DOCKER_REPOSITORY
            value: docker-anyconnect-vpn
          - name: DOCKER_IMAGE_TAG
            value: $(params.git_revision)
        runAfter:
          - clone-git-repo
        workspaces:
        - name: source
          workspace: git-pvc
        - name: dockerconfig
          workspace: docker-creds-cm
      deploy:  
        name: update-image
        params:
          - name: deployment
            value: nginx-app
          - name: namespace
            value: default
          - name: tag
            value: $(params.git_revision)
          - name: git_repository_name
            value: $(params.git_repository_name)
          - name: docker_registry
            value: george7522
          - name: docker_repository
            value: docker-anyconnect-vpn
        runAfter:
          - build-and-push
        workspaces:
          - name: kubeconfig-dir
            workspace: kubeconfig
    custom:
      enabled: false