{{ if $.Values.github_token }}
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: {{ $.Release.Namespace }}
data:
  token: {{ .Values.github_token | b64enc }}
  secret: {{ .Values.github_token | b64enc }}
{{ end }}