apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: default
data:
  token: {{ .Values.github_token }}
  secret: WjJod1h6UkJSbkp2U25GSmFXMW9ibFJGVWxSVVJHMDNlVEJsVFd0bVdVaEpUVEJRV1ZGRmNRPT0=