kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock