apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "generic.fullname" $ }}-tekton-default-sa"
---
{{- if .Values.pipelines }}
{{- range $value := .Values.pipelines }}
{{- range $taskcall := $value.taskcall }}
{{ if $taskcall.admin }} 
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: "{{ $.Release.Name }}-{{ $.Release.Namespace }}-{{ $taskcall.name }}"
  namespace: "{{ $.Release.Namespace }}"
{{ end }}
{{ end }}
{{ end }}
{{ end }}