name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.extract_version.outputs.new_version }}
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Extract version from Chart.yaml version
    - name: Extract version from Chart.yaml
      id: extract_version
      run: |
        # Extract version from Chart.yaml
        NEW_VERSION=$(grep '^version:' ./charts/tekton/Chart.yaml | sed 's/version: //')

        echo "Using version: $NEW_VERSION"
        echo "::set-output name=new_version::$NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV


    # Step 3: Set up Helm CLI
    - name: Set up Helm CLI
      uses: azure/setup-helm@v1
      with:
        version: v3.8.0

    # Step 4: Package the Helm chart
    - name: Package Helm chart
      run: |
        CHART_DIR="./charts/tekton"
        helm package $CHART_DIR --destination $CHART_DIR
      env:
        NEW_VERSION: ${{ env.NEW_VERSION }}

    # Step 5: Generate the SHA256 digest for the new .tgz file
    - name: Generate SHA256 digest for .tgz file
      run: |
        CHART_DIR="./charts/tekton"
        TGZ_FILE="$CHART_DIR/pipeline-${NEW_VERSION}.tgz"
        SHA256=$(shasum -a 256 "$TGZ_FILE" | awk '{print $1}')
        echo "Digest for $TGZ_FILE: $SHA256"

    # Step 6: Commit and push to gh-pages branch
    - name: Push to gh-pages
      run: |
        GH_PAGES_BRANCH="gh-pages"
        git fetch origin $GH_PAGES_BRANCH
        git checkout $GH_PAGES_BRANCH
        git fetch origin main
        git checkout main -- charts
        CHART_DIR="./charts/tekton"
        helm package $CHART_DIR --destination $CHART_DIR
        TGZ_FILE="$CHART_DIR/pipeline-${NEW_VERSION}.tgz"
        ls $CHART_DIR
        ls $TGZ_FILE
        mv "$TGZ_FILE" .
        if [ -f index.yaml ]; then
          helm repo index . --url https://cogitogrouptld.github.io/tekton-helm-chart --merge index.yaml
        else
          helm repo index . --url https://cogitogrouptld.github.io/tekton-helm-chart
        fi
        CHART_YAML_PATH="./charts/tekton/Chart.yaml"
        git config --global user.email "actions@github.com"
        git config --global user.name "$GITHUB_ACTOR"

        git add $CHART_YAML_PATH pipeline-${NEW_VERSION}.tgz index.yaml
        git commit -m "Release Helm chart version $NEW_VERSION"
        git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}" -f
        git push origin $GH_PAGES_BRANCH --tags --force
      env:
        NEW_VERSION: ${{ env.NEW_VERSION }}

    # Step 7: Create a GitHub Release and upload .tgz file
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ env.NEW_VERSION }}"
        files: ./charts/tekton/pipeline-${{ env.NEW_VERSION }}.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Step 8: Verify published version via Helm CLI
  verify:
    runs-on: ubuntu-latest
    needs: release

    steps:
    # Step 8.1: Set up Helm CLI
    - name: Set up Helm CLI
      uses: azure/setup-helm@v1
      with:
        version: v3.8.0

    # Step 8.2: Add Helm repo and update
    - name: Add Helm repo
      run: |
        helm repo add tekton-charts https://cogitogroupltd.github.io/tekton-helm-chart
        helm repo update

    # Step 8.3: Search Helm chart and verify version
    - name: Search Helm chart and verify version
      run: |
        helm search repo tekton-charts/pipeline
        helm show chart tekton-charts/pipeline --version ${{ needs.release.outputs.new_version }}
